services:

  prdback.com:
    restart: always
    build:
      context: ./back
      dockerfile: ../back.prod.Dockerfile
    ports:
      - '${BACK_PRD_PORT}:3000'
    volumes:
      - '${VOLUME_PRD_PATH}:/app/storage'
    networks:
      - database_default

  prdfront.com:
    restart: always
    build:
      dockerfile: ./front.Dockerfile
    ports:
      - '${FRONT_PRD_PORT}:3000'
    volumes:
      - './front:/app'

networks:
  database_default:
    external: true
