@APP_ID = 936619743392459

###
GET /api/v1/users/web_profile_info/?username=dlwlrm12312a HTTP/1.1
  Host: www.instagram.com
  Connection: keep-alive
  X-IG-App-ID: {{APP_ID}}
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Whale/3.21.192.18 Safari/537.36
